spring:
  application:
    name: movieflix


  datasource:
    url: jdbc:postgresql://localhost:5432/movieflix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:

    enabled: true

  jwt:
    secretKey: ",ye.*+r*?JEebfL-m8W5{6]5gXbMcdSYRVC}V(gE5@s0^M2Ff&Qdtd6F[~Fsa&I"